"""Configuration module exposing constants and reusable paths."""

from .constants import (
    DEFAULT_GRAD_CLIP_NORM,
    DEFAULT_LOG_EVERY_STEPS,
    HF_VIT_MODEL_ID,
    MINI_IMAGENET_DATASET_ID,
    SMALL_VLM_MODEL_ID,
)
from .paths import (
    DEFAULT_EXPL_DISTILL_PRECOMPUTE_OUTPUT_DIR,
    DEFAULT_EXPL_DISTILLED_STUDENT_OUTPUT_DIR,
    DEFAULT_FINETUNED_MODEL_BEST_DIR,
    DEFAULT_FINETUNED_MODEL_DIR,
    DEFAULT_FINETUNED_MODEL_FINAL_DIR,
    DEFAULT_FINETUNED_MODEL_PATH,
    DEFAULT_FINETUNED_OUTPUT_DIR,
    DEFAULT_GRADCAM_OUTPUT_FILE,
    DEFAULT_GRADCAM_OUTPUT_PATH,
    DEFAULT_VLM_FINETUNED_MODEL_DIR,
    DEFAULT_VLM_FINETUNED_OUTPUT_DIR,
    DEFAULT_VLM_PREPARED_MODEL_DIR,
    DEFAULT_VLM_PREPARED_OUTPUT_DIR,
    PROJECT_ROOT,
)

__all__ = [
    "DEFAULT_GRAD_CLIP_NORM",
    "DEFAULT_LOG_EVERY_STEPS",
    "HF_VIT_MODEL_ID",
    "MINI_IMAGENET_DATASET_ID",
    "SMALL_VLM_MODEL_ID",
    "DEFAULT_EXPL_DISTILL_PRECOMPUTE_OUTPUT_DIR",
    "DEFAULT_EXPL_DISTILLED_STUDENT_OUTPUT_DIR",
    "PROJECT_ROOT",
    "DEFAULT_FINETUNED_MODEL_DIR",
    "DEFAULT_FINETUNED_MODEL_BEST_DIR",
    "DEFAULT_FINETUNED_MODEL_FINAL_DIR",
    "DEFAULT_GRADCAM_OUTPUT_PATH",
    "DEFAULT_FINETUNED_MODEL_PATH",
    "DEFAULT_FINETUNED_OUTPUT_DIR",
    "DEFAULT_GRADCAM_OUTPUT_FILE",
    "DEFAULT_VLM_PREPARED_MODEL_DIR",
    "DEFAULT_VLM_FINETUNED_MODEL_DIR",
    "DEFAULT_VLM_PREPARED_OUTPUT_DIR",
    "DEFAULT_VLM_FINETUNED_OUTPUT_DIR",
]
