"""Filesystem path constants used across training and explainability."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DEFAULT_FINETUNED_MODEL_DIR = PROJECT_ROOT / "vit-mini-imagenet-finetuned"
DEFAULT_FINETUNED_MODEL_BEST_DIR = DEFAULT_FINETUNED_MODEL_DIR / "best"
DEFAULT_FINETUNED_MODEL_FINAL_DIR = DEFAULT_FINETUNED_MODEL_DIR / "final"
DEFAULT_GRADCAM_OUTPUT_PATH = PROJECT_ROOT / "gradcam_output.png"
DEFAULT_VLM_PREPARED_MODEL_DIR = PROJECT_ROOT / "vlm-vit-mini-imagenet-prepared"
DEFAULT_VLM_FINETUNED_MODEL_DIR = PROJECT_ROOT / "vlm-vit-mini-imagenet-finetuned"
DEFAULT_EXPL_DISTILL_PRECOMPUTE_DIR = PROJECT_ROOT / "expl-distill-precomputed"
DEFAULT_EXPL_DISTILLED_STUDENT_DIR = PROJECT_ROOT / "expl-distilled-student"

# String aliases for argparse defaults and user-facing settings.
DEFAULT_FINETUNED_MODEL_PATH = str(DEFAULT_FINETUNED_MODEL_BEST_DIR)
DEFAULT_FINETUNED_OUTPUT_DIR = str(DEFAULT_FINETUNED_MODEL_DIR)
DEFAULT_GRADCAM_OUTPUT_FILE = str(DEFAULT_GRADCAM_OUTPUT_PATH)
DEFAULT_VLM_PREPARED_OUTPUT_DIR = str(DEFAULT_VLM_PREPARED_MODEL_DIR)
DEFAULT_VLM_FINETUNED_OUTPUT_DIR = str(DEFAULT_VLM_FINETUNED_MODEL_DIR)
DEFAULT_EXPL_DISTILL_PRECOMPUTE_OUTPUT_DIR = str(DEFAULT_EXPL_DISTILL_PRECOMPUTE_DIR)
DEFAULT_EXPL_DISTILLED_STUDENT_OUTPUT_DIR = str(DEFAULT_EXPL_DISTILLED_STUDENT_DIR)
